services:
  backend:
    build: ./backend
    container_name: dcoy_backend
    ports:
      - "8000:8000"
    restart: always

  dashboard:
    build: ./dashboard
    container_name: dcoy_dashboard
    ports:
      - "8501:8501"
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
