"""API key store wrapper delegating to database ApiKeyRepository for backward compatibility."""

import logging
from typing import Optional
from app.database import SessionLocal
from app.repositories.user_repository import UserRepository
from app.repositories.api_key_repository import ApiKeyRepository

logger = logging.getLogger(__name__)

# Legacy in-memory dictionary export preserved for backward compatibility & test fixtures
api_keys_db = {}


def generate_api_key(user: str) -> str:
    """Generate and persist a new API key record for user via ApiKeyRepository."""
    db = SessionLocal()
    try:
        db_user = UserRepository.get_by_username(db, user)
        if not db_user:
            db_user = UserRepository.create_user(db, username=user, password="AutoGeneratedPassword123!")
            if not db_user:
                raise ValueError(f"Failed to bind API key: user '{user}' could not be resolved.")

        raw_key, _ = ApiKeyRepository.create_api_key(db, user_id=int(getattr(db_user, "id")), name="Generated API Key")
        return raw_key
    finally:
        db.close()


def validate_api_key(api_key: str) -> Optional[str]:
    """Validate raw API key against stored SHA-256 hash via ApiKeyRepository."""
    db = SessionLocal()
    try:
        db_user = ApiKeyRepository.validate_api_key(db, api_key)
        return str(getattr(db_user, "username")) if db_user else None
    finally:
        db.close()
