"""Attack Simulator service for coordinating purple team simulations and detection validation."""

import json
import time
import random
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from sqlalchemy.orm import Session
from app.models.simulation import DBSimulationRun
from app.models.detection_rule import DBDetectionRule
from app.services.rule_engine import RuleEngine
from app.services.simulation_engine import SimulationEngine


class AttackSimulator:
    """Coordinating service to execute synthetic simulations, check rule matches, and persist runs."""

    def __init__(self) -> None:
        self.rule_engine = RuleEngine()
        # In-memory cache for evaluation optimizations
        # Key: (scenario_name, rule_id, rule_version) -> Match Result
        self._evaluation_cache: Dict[str, Any] = {}

    def execute_simulation(self, db: Session, scenario_name: str, custom_params: Optional[Dict[str, Any]] = None) -> DBSimulationRun:
        """Run synthetic simulation, evaluate active rules, and save details to database."""
        custom_params = custom_params or {}
        started_at = datetime.now(timezone.utc)
        
        # 1. Generate synthetic telemetry
        telemetry = SimulationEngine.generate_scenario_telemetry(scenario_name, custom_params)
        
        # 2. Get active detection rules
        rules = db.query(DBDetectionRule).filter(DBDetectionRule.status == "Enabled").all()
        
        triggered_rules = []
        missed_rules = []
        timeline_events = []
        detected_event_indices = set()
        
        # Identify techniques generated by this scenario
        scenario_techniques = list(set(ev["mitre_technique"] for ev in telemetry if ev.get("mitre_technique")))
        
        # 3. Evaluate rules (with caching optimization)
        # Avoid duplicate evaluations by checking cache based on rule version and logic hash
        start_eval = time.perf_counter()
        
        for idx, event in enumerate(telemetry):
            event_detected = False
            matching_rules_for_event = []
            
            for rule in rules:
                rule_any: Any = rule
                cache_key = f"{scenario_name}_{rule_any.id}_{rule_any.version}_{idx}"
                
                # Performance Cache Check
                if cache_key in self._evaluation_cache:
                    is_match = self._evaluation_cache[cache_key]
                else:
                    is_match = self.rule_engine.evaluate_event(rule, event)
                    self._evaluation_cache[cache_key] = is_match
                
                if is_match:
                    event_detected = True
                    detected_event_indices.add(idx)
                    matching_rules_for_event.append({
                        "id": rule_any.id,
                        "name": rule_any.name,
                        "severity": rule_any.severity,
                        "category": rule_any.category,
                        "mitre_technique": rule_any.mitre_technique
                    })
                    if rule not in triggered_rules:
                        triggered_rules.append(rule)
            
            # Record detection latency (mock simulated value)
            latency = round(random.uniform(0.4, 2.8), 2) if event_detected else 0.0
            
            timeline_events.append({
                "timestamp": event["timestamp"],
                "technique": event.get("mitre_technique", "Unknown Technique"),
                "host": event.get("host", "Unknown Host"),
                "user": event.get("user", "Unknown User"),
                "severity": event.get("severity", "Medium"),
                "detection_status": "Detected" if event_detected else "Missed",
                "detection_latency_sec": latency,
                "matching_rules": matching_rules_for_event,
                "details": event.get("details", {})
            })
            
        # Determine missed rules (rules that map to this scenario's techniques but did not trigger)
        for rule in rules:
            rule_any: Any = rule
            if rule_any.mitre_technique in scenario_techniques and rule not in triggered_rules:
                missed_rules.append(rule)
                
        # 4. Compute KPIs
        total_events = len(telemetry)
        detected_events_count = len(detected_event_indices)
        missed_detections_count = total_events - detected_events_count
        
        success_rate = (detected_events_count / total_events) if total_events > 0 else 0.0
        
        # Coverage score = triggered rules / total relevant rules
        relevant_rules_count = len(triggered_rules) + len(missed_rules)
        coverage_score = (len(triggered_rules) / relevant_rules_count) if relevant_rules_count > 0 else 0.80
        
        # Average detection time
        latencies = [ev["detection_latency_sec"] for ev in timeline_events if ev["detection_status"] == "Detected"]
        avg_detection_time = sum(latencies) / len(latencies) if latencies else 0.0
        
        # Simulation confidence
        base_conf = 0.85
        if success_rate > 0.7:
            base_conf += 0.10
        if missed_detections_count == 0:
            base_conf += 0.03
        simulation_confidence = min(0.99, base_conf)
        
        completed_at = datetime.now(timezone.utc)
        
        # Formulate results JSON
        results_summary = {
            "triggered_rules": [
                {
                    "id": getattr(r, "id"),
                    "name": getattr(r, "name"),
                    "mitre_technique": getattr(r, "mitre_technique"),
                    "severity": getattr(r, "severity")
                } for r in triggered_rules
            ],
            "missed_rules": [
                {
                    "id": getattr(r, "id"),
                    "name": getattr(r, "name"),
                    "mitre_technique": getattr(r, "mitre_technique"),
                    "severity": getattr(r, "severity")
                } for r in missed_rules
            ],
            "timeline": timeline_events,
            "executive_summary": self.generate_executive_summary(
                success_rate, coverage_score, scenario_techniques, missed_rules, scenario_name
            )
        }
        
        # 5. Persist simulation run to SQLite db
        sim_run = DBSimulationRun(
            scenario_name=scenario_name,
            status="Completed",
            started_at=started_at,
            completed_at=completed_at,
            scanned_events_count=total_events,
            detection_success_rate=round(success_rate, 4),
            missed_detections_count=missed_detections_count,
            coverage_score=round(coverage_score, 4),
            average_detection_time_seconds=round(avg_detection_time, 2),
            simulation_confidence=round(simulation_confidence, 4),
            mitre_techniques=",".join(scenario_techniques),
            telemetry_data=json.dumps(telemetry),
            results_data=json.dumps(results_summary)
        )
        
        db.add(sim_run)
        db.commit()
        db.refresh(sim_run)
        
        return sim_run

    def generate_executive_summary(
        self,
        success_rate: float,
        coverage_score: float,
        techniques: List[str],
        missed_rules: List[DBDetectionRule],
        scenario_name: str
    ) -> Dict[str, Any]:
        """Generate executive summaries, gap analyses, and recommendations."""
        score = int(success_rate * 100)
        cov = int(coverage_score * 100)
        
        gaps = []
        improvements = []
        
        if score < 50:
            risk_summary = "CRITICAL DEFENSIVE GAP: Active detection signatures are insufficient to detect this adversary campaign style."
        elif score < 80:
            risk_summary = "MODERATE DEFENSIVE EXPOSURE: DcoY detects parts of the attack pipeline but misses critical execution or evasion techniques."
        else:
            risk_summary = "STRONG POSTURE: Defensive layers successfully trigger alerts across all stages of this simulation."
            
        # Identify gaps
        if not techniques:
            gaps.append("No MITRE techniques mapped for this scenario.")
        else:
            for tech in techniques[:2]:
                gaps.append(f"Potential blindspots on {tech} if primary rules are modified.")
                
        if missed_rules:
            for rule in missed_rules[:2]:
                rule_any: Any = rule
                gaps.append(f"Rule '{rule_any.name}' failed to match scenario telemetry due to threshold mismatches.")
                improvements.append(f"Optimize trigger threshold for rule: '{rule_any.name}' to cover dynamic attack variants.")
                
        # Fill default recommendations
        if not improvements:
            improvements.append("Deploy deception decoys specifically targeting initial access mechanisms.")
            improvements.append("Enable threat hunting queries to proactively search for anomalous registry tweaks.")
            
        improvements.append("Implement automated block response actions to immediately cut off malicious IP scopes.")
        
        return {
            "simulation_score": score,
            "coverage_score": cov,
            "major_gaps": gaps,
            "recommended_improvements": improvements,
            "risk_summary": risk_summary
        }
